# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_phonenum", "0002_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicecircuit",
            name="simultaneous_calls",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
