# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_phonenum", "0003_voicecircuit_simultaneous_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="pool",
            name="is_used",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="number",
            name="is_used",
            field=models.BooleanField(default=True),
        ),
    ]
