# Generated by Codex on 2026-06-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_phonenum", "0004_resource_is_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicecircuit",
            name="numbers",
            field=models.ManyToManyField(blank=True, related_name="voice_circuits", to="netbox_phonenum.number"),
        ),
        migrations.AddField(
            model_name="voicecircuit",
            name="pools",
            field=models.ManyToManyField(blank=True, related_name="voice_circuits", to="netbox_phonenum.pool"),
        ),
    ]
