# Generated by Codex on 2026-06-04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_phonenum", "0005_voicecircuit_phone_resources"),
    ]

    operations = [
        migrations.AlterField(
            model_name="number",
            name="pool",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="numbers",
                to="netbox_phonenum.pool",
            ),
        ),
    ]
