# Generated by Codex on 2026-06-05

import django.db.models.deletion
from django.db import migrations, models


def populate_number_tenant(apps, schema_editor):
    Number = apps.get_model("netbox_phonenum", "Number")

    for number in Number.objects.select_related("pool").filter(pool__isnull=False):
        number.tenant_id = number.pool.tenant_id
        number.save(update_fields=["tenant"])


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_phonenum", "0006_make_number_pool_optional"),
        ("tenancy", "0020_remove_contactgroupmembership"),
    ]

    operations = [
        migrations.AddField(
            model_name="number",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_numbers",
                to="tenancy.tenant",
            ),
        ),
        migrations.RunPython(populate_number_tenant, migrations.RunPython.noop),
    ]
